name: bazaaro_auth
publish_to: none
environment:
  sdk: ">=3.8.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  bazaaro_core:
    path: ../bazaaro_core
  bazaaro_domain:
    path: ../bazaaro_domain
  firebase_auth: ^5.3.4
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
dev_dependencies:
  flutter_lints: ^5.0.0
